IF NOT EXISTS(SELECT TOP 1 1 FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('[Crons].[Crons]')) BEGIN
	CREATE TABLE [Crons].[Crons](
		[CronID] [int] IDENTITY(1,1) NOT NULL,
		[Name] [nvarchar](100) NOT NULL,
		[SpName] [nvarchar](1024) NOT NULL,
	 CONSTRAINT [PK_Crons] PRIMARY KEY CLUSTERED 
	(
		[CronID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	PRINT 'CREATED [Crons].[Crons]'
END ELSE BEGIN
	PRINT 'ALREADY EXISTS [Crons].[Crons]'
END
GO
