IF NOT EXISTS(SELECT TOP 1 1 FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('[Users].[Assets]')) BEGIN
	CREATE TABLE [Users].[Assets](
		[UserID] [int] NOT NULL,
		[AssetIndex] [tinyint] NOT NULL,
		[AssetID] [int] NOT NULL,
		[AssetCrc] [int] NOT NULL,
	 CONSTRAINT [PK_Assets] PRIMARY KEY CLUSTERED 
	(
		[UserID] ASC,
		[AssetIndex] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	PRINT 'CREATED [Users].[Assets]'
END ELSE BEGIN
	PRINT 'ALREADY EXISTS [Users].[Assets]'
END
GO
