IF NOT EXISTS(SELECT TOP 1 1 FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('[Users].[Users]')) BEGIN
	CREATE TABLE [Users].[Users](
		[UserID] [int] NOT NULL,
		[RoomID] [smallint] NOT NULL,
		[Name] [nvarchar](100) NOT NULL,
		[Flags] [smallint] NOT NULL,
	 CONSTRAINT [PK_Users_1] PRIMARY KEY CLUSTERED 
	(
		[UserID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	PRINT 'CREATED [Users].[Users]'
END ELSE BEGIN
	PRINT 'ALREADY EXISTS [Users].[Users]'
END
GO
