IF NOT EXISTS(SELECT TOP 1 1 FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('[Saves].[DrawCmds]')) BEGIN
	CREATE TABLE [Saves].[DrawCmds](
		[UserID] [int] NOT NULL,
		[RoomID] [smallint] NOT NULL,
		[DrawCmdID] [int] NOT NULL,
		[DrawCmdType] [smallint] NOT NULL,
	 CONSTRAINT [PK_DrawCmds] PRIMARY KEY CLUSTERED 
	(
		[UserID] ASC,
		[RoomID] ASC,
		[DrawCmdID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	PRINT 'CREATED [Saves].[DrawCmds]'
END ELSE BEGIN
	PRINT 'ALREADY EXISTS [Saves].[DrawCmds]'
END
GO
