IF NOT EXISTS(SELECT TOP 1 1 FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('[Templates].[DrawCmds]')) BEGIN
	CREATE TABLE [Templates].[DrawCmds](
		[TemplateID] [int] NOT NULL,
		[DrawCmdID] [int] NOT NULL,
		[DrawCmdType] [smallint] NOT NULL,
	 CONSTRAINT [PK_DrawCmds] PRIMARY KEY CLUSTERED 
	(
		[TemplateID] ASC,
		[DrawCmdID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	PRINT 'CREATED [Templates].[DrawCmds]'
END ELSE BEGIN
	PRINT 'ALREADY EXISTS [Templates].[DrawCmds]'
END
GO
